# config/database.yml
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: ericsson
  password: Enabric123#  # You can leave this empty if there's no password
  host: localhost

development:
  <<: *default
  database: conversation_history_db_development

test:
  <<: *default
  database: conversation_history_db_test

production:
  <<: *default
  database: conversation_history_db_production
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
