
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: conversation_history_db_development
  host: localhost
  username: ericsson
  password: 'Enabric123#'
  port: 5432

  
  
test:
  <<: *default
  database: conversation_history_db_test
  host: localhost
  username: ericsson
  password: 'Enabric123#'
  port: 5432


production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

  
